### ISSUE TITLE
PA Review: New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by pangb86** [pangb86/Farther#1]
- [x] Back-end authentication pattern
- [x] Front- end authentication pattern
- [x] Presentational components
- [x] Adequate styling
- [x] Smooth, bug-free navigation

**Comment by AAlfarho** [comment]
Great job, styling, navigation, and overall functionality are working great!

**Comment by AAlfarho** [comment]
Great job! The style is really smooth and the navigation feels natural.
