### ISSUE TITLE
PA Review: Workouts

### ISSUE THREAD

**Issue by pangb86** [pangb86/Farther#4]
- [x] Users can create, view, and delete workouts
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Great job on the workouts, the change of the route depending on the dropdown looks great.
A couple of details.
+ Let's add some bottom margin to the map on the _show workout_ page.
+ I noticed the if we create a workout, when going back to the _workout index_ that workout is pushed all the way to the bottom, is this expected? My suggestion would be to have the most recent workout show up first, let's tackle that for a future release.
