### ISSUE TITLE
PA Review: Routes

### ISSUE THREAD

**Issue by pangb86** [pangb86/Farther#5]
- [x] Users can create, view, and delete custom routes
  - [x] Display a Google map on the page
  - [x] Center Google map on the user's geolocation
  - [x] Add ability to create a route by placing markers on the map
  - [x] Title box, create route button, toggle bicycle layer button added
  - [x] Display distance and elevation of the route
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Great work on the design of your routes, the information and help bubble text really caught my attention.
The overall look and feel and navigation feel smooth, kudos on that!

A couple of small details to consider for further iterations or revisions of this component.
+ The MVP did not include **edit**, it would be great to have it.
+ The help dialog (the question mark) states that we can drop several pins, as of now this is not the case, we could remove this, and add that section back, once that feature is enabled.
+ When we delete a route, it would be great if we could show a confirm modal to the user.
