### ISSUE TITLE
PA Review: Dashboard and profile

### ISSUE THREAD

**Issue by pangb86** [pangb86/Farther#6]
- [x] Users have a dashboard which displays their recorded workouts and their custom routes
- [x] Presentational components
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
The little dashboard nav complements the initial screen really well kudos on that.
This completes the last coding MVP!
