### ISSUE TITLE
PA Review: Workout Information

### ISSUE THREAD

**Issue by pangb86** [pangb86/Farther#7]
- [x] Workout feed displays the total stats for the user, including distance, speed, and elevation.
- [x] Each workout has its own information, including distance, speed, and elevation.
- [x] Presentational components
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Great job on the display of the workout information, the way it is incorporated as stats looks great.
